### ISSUE TITLE
How to request several tickers at once

### ISSUE THREAD

**Issue by cerezoafc** [vfilimonov/pydatastream#16] opened 2018-03-16 09:33 UTC
I want to request several tickers at once, for instance US and Spain's GDP.
I have no problem requesting each series one by one. but when I add a list of tickers, I get an error message. I cannot add a "field" because these series have no available field in Datastream, as far as I know.

**from pydatastream import Datastream
DWE = Datastream(username='DS:XXXXX', password='XXXXX')
DWE.fetch(['ESXGDPR.D','USGDP...D'], date_from='1980-01-01')**

invalid value encountered in absolute
  inside = ((abs(dx0 + dx1) + abs(dy0 + dy1)) == 0)
Traceback (most recent call last):

  File "<ipython-input-8-ea71ae83193e>", line 1, in <module>
    gdp = DWE.fetch(['ESXGDPR.D','USGDP...D'], date_from='1980-01-01')

  File "C:\Python27\lib\site-packages\pydatastream\pydatastream.py", line 513, in fetch
    dat, meta = self.parse_record(raw, indx)

  File "C:\Python27\lib\site-packages\pydatastream\pydatastream.py", line 295, in parse_record
    status['StatusMessage'], status['Request']))

DatastreamException: Failure (error 2): $$"ER", E100, INVALID CODE OR EXPRESSION ENTERED, USGDP...D(P) --> "ESXGDPR.D,USGDP...D~1980-01-01~D"

Thank you

**Comment by vfilimonov** [comment] 2018-03-17 20:59
This is a duplicate of https://github.com/vfilimonov/pydatastream/issues/11 (https://github.com/vfilimonov/pydatastream/issues/14 is also relevant).

Please see Note 1 in README.md for the explanations.

With respect to the GDP - you could try "ES" or "ESA" fields.

**Closed by vfilimonov** 2018-03-17 20:59 UTC
Labels: mnemonics and datatypes
